name: emilios_grocery
description: Food ordering app for Emilio's Grocery

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.3.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.2
  flutter_stripe: ^2.1.0
  google_maps_flutter: ^2.1.1
  sliding_up_panel: ^2.0.0+1
  http: ^0.13.3
  provider: ^5.0.0
  google_fonts: ^2.1.0
  flutter_svg: ^0.22.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/